blog/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views 
from django.contrib.auth.views import LogoutView

app_name = 'blog'

urlpatterns = [
    
    path('signup/',views.SiginUpView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="blog/registeration/login.html", next_page="/blog/"), name='login'),
    path('logout/',LogoutView.as_view(next_page='blog/login'), name='logout'),
    path('',views.PostListView.as_view(),name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',views.post_detial,name='post_detial'),
    path('<int:post_id>/comment/',views.comment_post,name='post_comment')
    

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls', namespace='blog')),
    
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse 
from django.utils.text import slugify


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED  ='PB', 'Published'

    title = models.CharField(max_length=100)
    content = models.TextField(default='new content')
    slug = models.SlugField(max_length=100,unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,choices=Status.choices,default=Status.DRAFT)
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def save(self,*args,**kwarqgs):

        if not self.slug:
            self.slug=slugify(self.title)

        super().save(*args,**kwarqgs)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detial",args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug,
        ])
    
class Comment(models.Model):

    name = models.CharField(max_length=80)
    body = models.TextField()
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'comment by {self.name} on {self.post}'
    

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','body']

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Post,Comment
from django.http import Http404
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.views.generic import ListView,CreateView
from .forms import CommentForm
from django.views.decorators.http import require_POST
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


class SiginUpView(CreateView):
    
    form_class = UserCreationForm
    success_url = reverse_lazy('blog:login')
    template_name = 'blog/registeration/signup.html'

    def form_valid(self, form):
        form.save()

        return redirect(self.success_url)
    
    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))
    
def profile_view(request):
    return render(request,'profile.html')

class PostListView(LoginRequiredMixin, ListView):

    model = Post
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog/post/list.html'
    login_url = 'login/'
    redirect_field_name = 'next'


@login_required(login_url='login/')   
def post_detial(request,year,month,day,post):

    post = get_object_or_404(Post, status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             
                             )
    comments= post.comments.filter(active=True)
    form = CommentForm()
    return render(request,'blog/post/detial.html',{'post':post,'comments':comments, 'form':form})


@login_required(login_url='login/')
@require_POST
def comment_post(request,post_id):

    post = get_object_or_404(Post,id=post_id,status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    
    
    return render(request,'blog/post/comment.html',{'form':form, 'post':post, 'comment':comment})

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static "css/blog.css" %}" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        
    </body>





</html>

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% block title %} Add a comment{% endblock %}

{% block content %}
    {% if comment %}
        <h2>your comment has been added. </h2>
        <p><a href="{{post.get_absolute_url}}">Back to the post</a></p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

blog/templates/blog/post/detial.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <P class="date">
    Published {{post.publish}} by {{post.author}}    
    </P>
    {{post.content|linebreaks}}
    
    {% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }} 
    </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{comment.created}}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p> there are no comments.</p>
    {% endfor %}
    {% include "blog/post/includes/comment_form.html" %}

{% endblock %}

blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url 'blog:post_comment' post.id %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <P><input type="submit" value="Add comment"></P>
</form>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}

   <h1>My blog</h1>
   {% for post in posts %}
       <h2>
        <a href="{{post.get_absolute_url}}">
            {{post.title}}
        </a>
       </h2>
       <p class="date">
        Published {{ post.publish }} by {{ post.author }}
       </p>
       {{ post.content|truncatewords:30|linebreaks }}

   {% endfor %} 
   {% include "pagination.html" with page=page_obj %}
{% endblock %}
      

blog/templates/blog/registeration/login.html
<h1>login</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">login</button>
</form>

blog/templates/blog/registeration/signup.html
<h1>registeration</h1>


<form method="post" action="{% url 'blog:signup' %}">
    {% csrf_token %}
    <div>
        <label for="{{ form.username.id_for_label }}">username:</label>
        {{ form.username }}
    </div>

    <div>
        <label for="{{ form.password1.id_for_label }}">password:</label>
        {{ form.password1 }}
    </div>

    <div>
        <label for="{{ form.password2.id_for_label }}">confirm password:</label>
        {{ form.password2 }}
    </div>

    <button type="submit">register</button>
</form>
{% if form.errors %}
    <ul style="color: red;">
        {% for field, errors in form.errors.items %}
            {% for error in errors %}
                <li>{{ field|capfirst }}: {{ error }}</li>
            {% endfor %}
        {% endfor %}
    </ul>
{% endif %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Pervious</a>
        {% endif %}
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span> 
    {% if page.has_next %} 
        <a href="?page={{ page.next_page_number }}">Next</a> 
    {% endif %} 
    </span>
</div>